### ISSUE TITLE
ssh执行脚本没有权限，我要在哪里设置呢？

### ISSUE THREAD

**Issue by zouhuigang** [prontera/docker-mysql-mha#1]
>>> Setting ssh...
469d5155e20d initializing SSH...
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:24
7: starting container process caused "exec: \"/preparation/ssh-init.sh\": permis
sion denied"

**Comment by prontera** [comment]
您好，请为该sh脚本添加x执行权限。

**Comment by zouhuigang** [comment]
docker@default:/mnt-linux/docker-mysql-mha/mha_manager/preparation$ chmod +x ssh-init.sh 
docker@default:/mnt-linux/docker-mysql-mha/mha_manager/preparation$ chmod +x ssh-pass.sh 
docker@default:/mnt-linux/docker-mysql-mha/mha_manager/preparation$

**Comment by zouhuigang** [comment]
>>> Setting ssh... 
dc3401646c69 initializing SSH...
dc3401646c69 change the password of root successfully.
dc3401646c69 SSH service has been restarted.
dc3401646c69 succeed in generating ssh key.
no such file or directory
[root@k8s-master docker-mysql-mha]#

**Comment by zouhuigang** [comment]
这又是什么问题。。。复制什么出错？

**Comment by zouhuigang** [comment]
谢谢~~
